import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, "..");

test("Vue UI keeps Chinese Git-safe commit-first workbench structure", async () => {
  const app = await readFile(path.join(root, "src", "App.vue"), "utf8");
  const css = await readFile(path.join(root, "src", "styles.css"), "utf8");
  const server = await readFile(path.join(root, "server.mjs"), "utf8");
  const graphCss = await readFile(path.join(root, "src", "styles", "graph.css"), "utf8");
  const clientApi = await readFile(path.join(root, "src", "client", "api.js"), "utf8");
  const rail = await readFile(path.join(root, "src", "components", "Rail.vue"), "utf8");
  const gitGraphView = await readFile(path.join(root, "src", "views", "GitGraphView.vue"), "utf8");
  const workflowView = await readFile(path.join(root, "src", "views", "WorkflowView.vue"), "utf8");
  const settingsView = await readFile(path.join(root, "src", "views", "SettingsView.vue"), "utf8");
  const settingsModel = await readFile(path.join(root, "src", "settings-model.js"), "utf8");
  const graphLayout = await readFile(path.join(root, "src", "graph-layout.js"), "utf8");
  const packageRelease = await readFile(path.join(root, "package-release.ps1"), "utf8");
  const selectableFilesWatch = workflowView.match(/watch\(\(\) => props\.selectableFiles,[\s\S]*?\}, \{ immediate: true \}\);/)?.[0] || "";

  assert.match(app, /const zh = \{/);
  assert.match(app, /title: "Git 安全提交"/);
  assert.match(app, /fetchRemote: "获取远端"/);
  assert.match(app, /openTextWorkbench: "打开文本工作台"/);
  assert.match(app, /exportBinaryConflict: "导出二进制版本"/);
  assert.match(app, /openBinaryWorkbench: "打开二进制工作台"/);
  assert.match(app, /writeConflictCandidate: "生成候选文件"/);
  assert.match(app, /aiCommit: "提交选中文件"/);
  assert.match(app, /commitQueue: "提交队列"/);
  assert.match(app, /commitMessage: "提交说明"/);
  assert.match(app, /forbidPull: "禁止 git pull"/);
  assert.match(app, /forbidReset: "禁止 reset --hard"/);

  assert.match(app, /class="app-shell"/);
  assert.match(rail, /class="rail"/);
  assert.match(rail, /class="setup-card"/);
  assert.match(rail, /class="rail-tools"/);
  assert.match(rail, /class="rail-tool"/);
  assert.match(app, /const themeMode = ref\(/);
  assert.match(app, /const railCollapsed = ref\(false\)/);
  assert.match(app, /function toggleTheme\(\)/);
  assert.match(app, /function toggleRail\(\)/);
  assert.match(rail, /themeMode === 'dark' \? '浅色模式' : '暗色模式'/);
  assert.match(rail, /railCollapsed \? '展开' : '收起'/);
  assert.match(rail, /class="main-nav"/);
  assert.match(app, /const activeView = ref\("workflow"\)/);
  assert.doesNotMatch(app, /const activeSettingsTab = ref\("general"\)/);
  assert.match(settingsView, /const activeSettingsTab = ref\("general"\)/);
  assert.match(settingsView, /const settingsTabs = \[/);
  assert.match(settingsView, /@click="activeSettingsTab = tab\.id"/);
  assert.match(settingsView, /activeSettingsTab === 'ai'/);
  assert.match(settingsView, /activeSettingsTab === 'repo'/);
  assert.match(settingsView, /activeSettingsTab === 'safety'/);
  assert.match(settingsView, /activeSettingsTab === 'local'/);
  assert.match(settingsView, /form\.selectedAi/);
  assert.match(app, /aiInstallations: \[\]/);
  assert.match(app, /toolVersion: ""/);
  assert.match(app, /loadHealth\(\)/);
  assert.match(app, /view\.toolVersion = health\.version \|\| ""/);
  assert.match(app, /:tool-version="view\.toolVersion"/);
  assert.match(rail, /toolVersion: \{ type: String, default: "" \}/);
  assert.match(rail, /class="version-pill"/);
  assert.match(clientApi, /export async function loadHealth/);
  assert.match(clientApi, /"\/api\/health"/);
  assert.match(css, /\.version-pill/);
  assert.match(css, /\.theme-light \.version-pill/);
  assert.match(packageRelease, /npm version patch --no-git-tag-version/);
  assert.match(packageRelease, /\$Version = \$nextVersion/);
  assert.match(app, /const installedAi = computed/);
  assert.match(app, /const selectedAi = computed/);
  assert.match(clientApi, /export async function loadGraph/);
  assert.match(clientApi, /"\/api\/git\/graph"/);
  assert.match(clientApi, /export async function loadRepoFileDiff/);
  assert.match(clientApi, /"\/api\/git\/file-diff"/);
  assert.match(clientApi, /export async function loadTextConflict/);
  assert.match(clientApi, /export async function writeTextCandidate/);
  assert.match(clientApi, /export async function loadTableConflict/);
  assert.match(clientApi, /export async function writeTableCandidate/);
  assert.match(clientApi, /export async function loadBinaryConflict/);
  assert.match(clientApi, /export async function writeBinaryCandidate/);
  assert.match(clientApi, /export async function applyConflictCandidate/);
  assert.match(clientApi, /export async function openRepoFile/);
  assert.match(clientApi, /export async function exportBinaryConflict/);
  assert.doesNotMatch(clientApi, /export async function commitAssistWithAi/);
  assert.doesNotMatch(clientApi, /"\/api\/ai\/commit-assist"/);
  assert.match(server, /"\/api\/conflict\/binary\/load"/);
  assert.match(server, /"\/api\/conflict\/binary\/candidate"/);
  assert.match(server, /"\/api\/conflict\/candidate\/apply"/);
  assert.match(clientApi, /export function openEvents/);
  assert.match(server, /openLocalFile\(target\.fullPath\)/);
  assert.doesNotMatch(server, /openLocalFile\(target\.absolute\)/);
  assert.match(app, /loadAiInstallations\(\)/);
  assert.doesNotMatch(app, /fetch\(/);
  assert.doesNotMatch(app, /api\("\/api\/git\/graph"\)/);
  assert.match(settingsView, /buildSettingsPayload\(form\)/);
  assert.match(settingsView, /fillSettingsFormFromConfig\(form, config/);
  assert.match(settingsView, /function chooseRepoFolder\(\)/);
  assert.match(settingsView, /emit\("choose-repo-folder"/);
  assert.match(clientApi, /new WebSocket\(eventSocketUrl\("\/api\/events"\)\)/);
  assert.doesNotMatch(clientApi, /new EventSource/);
  assert.match(server, /new WebSocketServer\(\{ server, path: "\/api\/events" \}\)/);
  assert.doesNotMatch(server, /text\/event-stream/);
  assert.match(settingsView, /if \(path\) \{\s*form\.repoPath = path;\s*emit\("save", buildSettingsPayload\(form\)\);\s*\}/);
  assert.match(settingsView, /class="repo-path-picker wide"/);
  assert.match(settingsView, /v-model="form\.repoPath"/);
  assert.match(settingsView, /@click="chooseRepoFolder"/);
  assert.match(settingsView, /class="repo-history wide"/);
  assert.match(settingsView, /v-for="repo in form\.repositories"/);
  assert.match(settingsView, /@click="switchRepo\(repo\)"/);
  assert.match(settingsView, /emit\("switch-repo"/);
  assert.doesNotMatch(app, /hasConfiguredAiKey\(view\.config\)/);
  assert.match(settingsModel, /selectedAi: "codex"/);
  assert.match(settingsModel, /ai: \{\s*selected,/);
  assert.match(settingsView, /class="ai-picker wide"/);
  assert.match(settingsView, /class="ai-option"/);
  assert.match(settingsView, /@click="form\.selectedAi = ai\.id"/);
  assert.match(app, /activeView === 'workflow'/);
  assert.match(app, /activeView === 'graph'/);
  assert.match(app, /activeView === 'settings'/);
  assert.match(app, /<section v-show="activeView === 'workflow'" class="view-pane">/);
  assert.match(app, /<section v-show="activeView === 'graph'" class="view-pane">/);
  assert.match(app, /<section v-show="activeView === 'settings'" class="view-pane">/);
  assert.doesNotMatch(app, /<WorkflowView\s+v-if="activeView === 'workflow'"/);
  assert.doesNotMatch(app, /<GitGraphView\s+v-if="activeView === 'graph'"/);
  assert.doesNotMatch(app, /<SettingsView\s+v-if="activeView === 'settings'"/);
  assert.match(rail, />提交工作流</);
  assert.match(rail, />git 树</);
  assert.match(rail, />设置</);
  assert.match(settingsView, /class="settings-page"/);
  assert.match(settingsView, /class="settings-tabs"/);
  assert.match(settingsView, /class="settings-card"/);
  assert.match(settingsView, /class="setting-alert wide"/);
  assert.match(settingsView, /class="ai-picker wide"/);
  assert.match(workflowView, /class="command-bar"/);
  assert.match(workflowView, /class="commit-card"/);
  assert.match(workflowView, /class="queue-list"/);
  assert.match(workflowView, /class="disabled-reason"/);
  assert.match(workflowView, /emit\("commit"/);
  assert.match(workflowView, /paths: selectedPaths\.value/);
  assert.match(workflowView, /async function ensureCommitMessage/);
  assert.match(workflowView, /const message = await ensureCommitMessage\(\)/);
  assert.match(workflowView, /emit\("commit", \{ paths: selectedPaths\.value, message \}\)/);
  assert.match(workflowView, /function confirmDiscardSelected\(\)/);
  assert.match(workflowView, /confirmAction\.value = "discard-selected"/);
  assert.match(workflowView, /emit\("action", "discard-selected", \{ paths: selectedPaths\.value, confirmed: true \}\)/);
  assert.match(workflowView, /class="btn danger discard-selected"/);
  assert.match(css, /\.theme-dark \.commit-actions \.btn\.danger/);
  assert.doesNotMatch(workflowView, /if \(!commitMessage\.value\.trim\(\)\) return/);
  assert.match(workflowView, /class="commit-actions"[\s\S]*@click="suggestMessage"[\s\S]*@click="runCommit"/);
  assert.match(workflowView, /AI 生成详细说明/);
  assert.match(app, /runAction\("commit", payload\)/);
  assert.doesNotMatch(app, /runAction\("ai-commit", payload\)/);
  assert.match(app, /const conflictCandidates = ref\(\{\}\)/);
  assert.match(app, /const displayedBlockers = computed/);
  assert.match(app, /function rememberConflictCandidate\(payload\)/);
  assert.match(app, /applyConflictCandidate as applyConflictCandidateApi/);
  assert.match(app, /async function applyConflictCandidate\(payload, done\)/);
  assert.match(app, /unmerged files present/);
  assert.match(app, /formatBlocker\(blocker, candidateCount, unmergedCount\)/);
  assert.match(app, /候选文件只是草稿，还没有应用到原冲突文件/);
  assert.match(app, /原文件仍包含冲突标记/);
  assert.doesNotMatch(app, /工作区格式检查未通过/);
  assert.match(workflowView, /commitResetKey/);
  assert.match(app, /commitResetKey\.value \+= 1/);
  assert.match(app, /const operationNotice = ref\(null\)/);
  assert.match(app, /audit: null/);
  assert.match(app, /const audit = computed/);
  assert.match(app, /const riskByPath = computed/);
  assert.match(app, /risk: riskByPath\.value\.get\(file\.path\)/);
  assert.match(app, /:audit="audit"/);
  assert.match(app, /const AuditRefreshIntervalMs = 3000/);
  assert.match(app, /let auditRefreshTimer = 0/);
  assert.match(app, /function startAuditRefresh\(\)/);
  assert.match(app, /setInterval\(refreshAuditNow, AuditRefreshIntervalMs\)/);
  assert.match(app, /function canRefreshAudit\(\)/);
  assert.match(app, /document\.visibilityState !== "hidden"/);
  assert.match(app, /async function refreshAuditNow\(\)/);
  assert.match(app, /if \(view\.busy\) return/);
  assert.match(clientApi, /export async function refreshAudit\(\)/);
  assert.match(clientApi, /request\("\/api\/audit\/refresh"\)/);
  assert.match(app, /refreshAuditApi\(\)/);
  assert.match(app, /view\.audit = result\.audit \|\| null/);
  assert.match(app, /showOperationNotice\(/);
  assert.match(app, /showOperationFailureNotice\(/);
  assert.match(app, /function explainFailure\(action, error = \{\}\)/);
  assert.match(app, /selected-paths-stale/);
  assert.match(app, /选择已过期/);
  assert.match(app, /提交安全检查已拦截/);
  assert.match(app, /clearStaleOperationNotice\(/);
  assert.match(app, /isRemoteAdvancedPushMessage/);
  assert.match(app, /error\.data\?\.reason/);
  assert.match(app, /error\.data\?\.recommendedAction/);
  assert.match(app, /AI 判断：先同步远端/);
  assert.match(app, /action: "ai-sync-and-push"/);
  assert.match(app, /clearOperationNotice/);
  assert.match(app, /operationNotice\.value = null/);
  assert.match(app, /:operation-notice="operationNotice"/);
  assert.match(workflowView, /operationNotice: \{ type: Object, default: null \}/);
  assert.match(workflowView, /logs: \{ type: Array, default: \(\) => \[\] \}/);
  assert.match(workflowView, /details: \{ type: String, default: "" \}/);
  assert.match(workflowView, /audit: \{ type: Object, default: null \}/);
  assert.match(workflowView, /const auditTone = computed/);
  assert.match(workflowView, /const auditActionableFindings = computed/);
  assert.match(workflowView, /const auditIsExpanded = computed/);
  assert.match(workflowView, /const auditSummaryText = computed/);
  assert.match(workflowView, /const auditConfirmationText = computed/);
  assert.match(workflowView, /需确认文件/);
  assert.match(workflowView, /确认方式：在已解决冲突确认区逐个查看暂存 diff/);
  assert.match(workflowView, /class="audit-confirmation-line"/);
  assert.match(workflowView, /提交安全检查：/);
  assert.match(workflowView, /class="audit-card"/);
  assert.match(workflowView, /compact: !auditIsExpanded/);
  assert.match(workflowView, /audit\.counts\?\.discardStash/);
  assert.match(workflowView, /const hasRestorableToolStashes = computed/);
  assert.match(workflowView, /Number\(props\.audit\?\.counts\?\.discardStash \|\| 0\) > 0/);
  assert.match(workflowView, /class="audit-action"/);
  assert.match(workflowView, /恢复并清理/);
  assert.match(workflowView, /emit\("action", "restore-tool-stashes"\)/);
  assert.match(app, /"restore-tool-stashes"/);
  assert.match(app, /stash 已恢复并清理/);
  assert.match(css, /\.audit-action/);
  assert.match(workflowView, /class="file-risk-tags"/);
  assert.match(workflowView, /function riskLabel\(label\)/);
  assert.match(workflowView, /emit\("clear-operation-notice"\)/);
  assert.match(workflowView, /class="operation-notice"/);
  assert.match(workflowView, /operationNotice\.tone/);
  assert.match(workflowView, /operationNotice\.title/);
  assert.match(workflowView, /operationNotice\.message/);
  assert.match(workflowView, /const pushFollowupAction = computed/);
  assert.match(workflowView, /const remotePrimaryAction = computed/);
  assert.match(workflowView, /const remoteDivergenceTone = computed/);
  assert.match(workflowView, /ahead > 0 && behind > 0/);
  assert.match(workflowView, /props\.summary\?\.ahead && !props\.summary\?\.cleanWorktree/);
  assert.match(workflowView, /behind > 0/);
  assert.match(workflowView, /ahead > 0/);
  assert.match(workflowView, /const worktreeTone = computed/);
  assert.match(workflowView, /:class="remoteDivergenceTone"/);
  assert.match(workflowView, /:class="worktreeTone"/);
  assert.match(workflowView, /const pushActionLabel = computed/);
  assert.match(workflowView, /AI 同步后推送/);
  assert.match(workflowView, /confirmAction\.value = pushFollowupAction\.value/);
  assert.match(workflowView, /emit\("action", "ai-sync-and-push", \{ confirmed: true \}\)/);
  assert.match(workflowView, /function runRemoteAction\(\)/);
  assert.match(workflowView, /@click="runRemoteAction"/);
  assert.doesNotMatch(workflowView, /class="btn sync-btn"/);
  assert.match(workflowView, /aria-label="关闭操作提示"/);
  assert.match(css, /\.operation-notice/);
  assert.match(css, /\.operation-notice\.success/);
  assert.match(css, /\.operation-notice\.warning/);
  assert.match(css, /\.audit-card/);
  assert.match(css, /\.audit-card\.bad/);
  assert.match(css, /\.audit-confirmation-line/);
  assert.match(css, /\.file-risk-tags/);
  assert.match(css, /\.theme-dark \.audit-card/);
  assert.match(workflowView, /emit\("action", "push", \{ confirmed: true \}\)/);
  assert.doesNotMatch(workflowView, /emit\("push", \{ confirmed: true \}\)/);
  assert.doesNotMatch(workflowView, /"push", "load-text-conflict"/);
  assert.doesNotMatch(app, /@push="runPush"/);
  assert.match(workflowView, /emit\("action", "continue-rebase-and-push", \{ confirmed: true \}\)/);
  assert.match(workflowView, /emit\("action", "abort-rebase", \{ confirmed: true \}\)/);
  assert.match(workflowView, /confirmAction\.value = "abort-rebase"/);
  assert.match(workflowView, /const canAbortRebase = computed\(\(\) => rebaseInProgress\.value && !props\.busy\)/);
  assert.match(workflowView, /v-if="canAbortRebase"/);
  assert.match(workflowView, /rebase-reset-action/);
  assert.match(workflowView, /emit\("action", "ai-sync"\)/);
  assert.doesNotMatch(workflowView, /emit\("action", "sync"\)/);
  assert.match(app, /const repositoryChangingActions = new Set/);
  assert.match(app, /repositoryChangingActions\.has\(action\)/);
  assert.match(app, /"discard-selected"/);
  assert.match(app, /async function refreshRepositoryView/);
  assert.match(app, /isExcelCloseRequiredFailure\(error\)/);
  assert.match(app, /close-excel-and-retry/);
  assert.match(app, /window\.alert\(message\)/);
  assert.match(app, /await refreshRepositoryView\(\{ inspect: true \}\)/);
  assert.match(app, /catch \(error\)[\s\S]*refreshRepositoryView\(\{ inspect: true \}\)/);
  assert.match(workflowView, /const rebaseInProgress = computed/);
  assert.match(workflowView, /继续变基并推送/);
  assert.match(workflowView, /rebaseInProgress\.value/);
  assert.match(workflowView, /class="[^"]*conflict-box/);
  assert.match(workflowView, /function openTextWorkbench\(path\)/);
  assert.match(workflowView, /function openTableWorkbench\(path\)/);
  assert.doesNotMatch(workflowView, /autoResolveTableConflict/);
  assert.match(workflowView, /Merge 待提交/);
  assert.match(workflowView, /mergeCommitMessage/);
  assert.match(workflowView, /v-if="!mergeInProgress"/);
  assert.match(app, /Merge 已提交/);
  assert.match(workflowView, /function openBinaryWorkbench\(path\)/);
  assert.match(workflowView, /prefab\|asset\|meta/);
  assert.match(workflowView, /csv\|tsv\|xlsx/);
  assert.match(app, /"sync"/);
  assert.match(app, /loadConfigAndState\(\), loadGraph\(\)/);
  assert.match(workflowView, /function saveTextCandidate\(\)/);
  assert.match(workflowView, /function saveTableCandidate\(\)/);
  assert.match(workflowView, /function saveBinaryCandidate\(\)/);
  assert.match(workflowView, /function openGeneratedCandidate\(\)/);
  assert.match(workflowView, /candidateResultsByPath/);
  assert.match(workflowView, /function rememberCandidateResult\(path, candidate, message\)/);
  assert.match(workflowView, /function restoreCandidateResult\(path, fallbackMessage\)/);
  assert.match(workflowView, /"candidate-created"/);
  assert.match(workflowView, /function conflictCandidateFor\(file\)/);
  assert.match(workflowView, /function conflictRowClass\(file\)/);
  assert.match(workflowView, /const conflictQueueSummary = computed/);
  assert.match(workflowView, /const resolvedRebaseReviewFiles = computed/);
  assert.match(workflowView, /const resolvedRebaseRiskFiles = computed/);
  assert.match(workflowView, /const resolvedRebaseReviewSummary = computed/);
  assert.match(workflowView, /const canReviewResolvedRebaseWithAi = computed/);
  assert.doesNotMatch(workflowView, /const selectedReviewFiles = computed/);
  assert.doesNotMatch(workflowView, /const canReviewSelectedFilesWithAi = computed/);
  assert.doesNotMatch(workflowView, /const canRunCommitAssistWithAi = computed/);
  assert.doesNotMatch(workflowView, /const selectionAiReviewVisible = computed/);
  assert.doesNotMatch(workflowView, /const aiReviewContextText = computed/);
  assert.match(workflowView, /const aiReviewTarget = ref\(""\)/);
  assert.doesNotMatch(workflowView, /const aiReviewPaths = ref\(\[\]\)/);
  assert.match(workflowView, /const aiReviewRepoPath = ref\(""\)/);
  assert.match(workflowView, /let aiReviewRequestId = 0/);
  assert.match(workflowView, /function clearAiReview\(target = ""\)/);
  assert.match(workflowView, /function beginAiReview\(target\)/);
  assert.doesNotMatch(workflowView, /function pathSignature\(paths\)/);
  assert.match(workflowView, /watch\(\(\) => props\.config\?\.repoPath,[\s\S]*clearAiReview\(\)/);
  assert.doesNotMatch(workflowView, /watch\(selectedPaths,[\s\S]*clearAiReview\("selection"\)/);
  assert.doesNotMatch(selectableFilesWatch, /clearAiReview/);
  assert.match(workflowView, /watch\(\(\) => props\.commitResetKey,[\s\S]*clearAiReview\(\)/);
  assert.match(workflowView, /function fileChangeKind\(file\)/);
  assert.match(workflowView, /function fileChangeLabel\(file\)/);
  assert.match(workflowView, /function fileStatusText\(file\)/);
  assert.match(workflowView, /added: "新增"/);
  assert.match(workflowView, /updated: "更新"/);
  assert.match(workflowView, /deleted: "删除"/);
  assert.match(workflowView, /fileChangeLabel\(file\)/);
  assert.match(workflowView, /class="file-status-line"/);
  assert.match(workflowView, /class="change-kind"/);
  assert.match(workflowView, /change-\$\{fileChangeKind\(file\)\}/);
  assert.match(workflowView, /fileStatusText\(detailQueueFile\)/);
  assert.match(workflowView, /<span>{{ fileChangeLabel\(file\) }} · {{ file\.status }}<\/span>/);
  assert.match(workflowView, /function reviewResolvedRebaseWithAi\(\)/);
  assert.doesNotMatch(workflowView, /function reviewSelectedFilesWithAi\(\)/);
  assert.doesNotMatch(workflowView, /function suggestMessageAndReview\(\)/);
  assert.doesNotMatch(workflowView, /emit\("commit-assist", \{ paths: reviewPaths, risks \}/);
  assert.doesNotMatch(workflowView, /commitMessage\.value = result\.message\.trim\(\)/);
  assert.match(workflowView, /const requestId = beginAiReview\("rebase"\)/);
  assert.doesNotMatch(workflowView, /const requestId = beginAiReview\("selection"/);
  assert.match(workflowView, /requestId !== aiReviewRequestId \|\| aiReviewTarget\.value !== "rebase"/);
  assert.doesNotMatch(workflowView, /requestId !== aiReviewRequestId \|\| aiReviewTarget\.value !== "selection"/);
  assert.match(workflowView, /aiReviewRepoPath\.value !== \(props\.config\?\.repoPath \|\| ""\)/);
  assert.match(workflowView, /已解决冲突确认/);
  assert.match(workflowView, /冲突工作台只在 Git 仍有未合并文件时显示/);
  assert.match(workflowView, /查看暂存 diff/);
  assert.match(workflowView, /AI 审查暂存结果/);
  assert.doesNotMatch(workflowView, /AI 审查所选/);
  assert.doesNotMatch(workflowView, /AI 说明\+审查/);
  assert.match(workflowView, /AI 只给建议，不会替你确认或继续变基/);
  assert.match(workflowView, /"review-audit"/);
  assert.doesNotMatch(workflowView, /"commit-assist"/);
  assert.match(workflowView, /diffScope: "staged"/);
  assert.doesNotMatch(workflowView, /diffScope: "combined"/);
  assert.doesNotMatch(workflowView, /class="ai-review-btn queue-review-btn"/);
  assert.doesNotMatch(workflowView, /class="selection-review-panel"/);
  assert.doesNotMatch(workflowView, /class="ai-review-panel-head"/);
  assert.doesNotMatch(workflowView, /class="ai-review-pending"/);
  assert.doesNotMatch(workflowView, /selection-review-result/);
  assert.doesNotMatch(workflowView, /selection-review-error/);
  assert.match(workflowView, /class="ai-review-btn"/);
  assert.doesNotMatch(workflowView, /loading: busy === 'ai-audit-review' && aiReviewTarget === 'selection'/);
  assert.match(workflowView, /loading: busy === 'ai-audit-review' && aiReviewTarget === 'rebase'/);
  assert.match(app, /reviewAuditWithAi as reviewAuditWithAiApi/);
  assert.doesNotMatch(app, /commitAssistWithAi as commitAssistWithAiApi/);
  assert.doesNotMatch(app, /async function commitAssistWithAi\(payload, done\)/);
  assert.doesNotMatch(app, /view\.busy = "ai-commit-assist"/);
  assert.doesNotMatch(app, /@commit-assist="commitAssistWithAi"/);
  assert.match(app, /@review-audit="reviewAuditWithAi"/);
  assert.doesNotMatch(server, /suggestCommitMessageAndReview/);
  assert.doesNotMatch(server, /"\/api\/ai\/commit-assist"/);
  assert.match(server, /const diffScope = req\.body\.diffScope === "combined" \? "combined" : "staged"/);
  assert.match(server, /reviewAuditWithAi\(\{ config, paths, risks, diffScope \}\)/);
  assert.match(workflowView, /class="resolved-rebase-box"/);
  assert.match(workflowView, /class="resolved-review-row"/);
  assert.match(workflowView, /class="ai-review-result"/);
  assert.match(workflowView, /function conflictWorkbenchType\(file\)/);
  assert.match(workflowView, /function conflictWorkbenchLabel\(file\)/);
  assert.match(workflowView, /function conflictNeedsManualReview\(file\)/);
  assert.match(workflowView, /function conflictGuidance\(file\)/);
  assert.match(workflowView, /"apply-candidate"/);
  assert.match(workflowView, /function applyCandidateFor\(file\)/);
  assert.match(workflowView, /应用候选并暂存/);
  assert.match(workflowView, /candidate-ready/);
  assert.match(workflowView, /candidate-missing/);
  assert.match(workflowView, /manual-review/);
  assert.match(workflowView, /候选已生成/);
  assert.match(workflowView, /待生成候选/);
  assert.match(workflowView, /function highlightedCode\(content\)/);
  assert.match(workflowView, /isLargeTextCandidate/);
  assert.match(workflowView, /highlightedTextCandidate/);
  assert.match(workflowView, /function isLargeHighlightedContent\(content\)/);
  assert.match(workflowView, /function scheduleTextCandidateRefresh\(\)/);
  assert.match(workflowView, /function currentTextCandidateContent\(\)/);
  assert.match(workflowView, /content,\s*source: textDraftSource\.value/);
  assert.match(workflowView, /function protectFieldDeclarations\(content, tokens\)/);
  assert.match(workflowView, /function protectVariableNames\(content, tokens\)/);
  assert.match(workflowView, /typeof maybeName === "string"/);
  assert.match(workflowView, /function syncCandidateHighlightScroll\(event\)/);
  assert.match(workflowView, /function exportBinary\(path\)/);
  assert.match(workflowView, /buildTableMerge/);
  assert.match(workflowView, /composeTableDraft/);
  assert.match(workflowView, /composeTableRows/);
  assert.match(workflowView, /tableChoiceSummary/);
  assert.match(workflowView, /tableAlignmentMode/);
  assert.match(workflowView, /tableKeyColumnOptions/);
  assert.match(workflowView, /function setTableAlignmentMode\(mode\)/);
  assert.match(workflowView, /function setTableKeyColumn\(column\)/);
  assert.match(workflowView, /class="table-alignment-panel"/);
  assert.match(workflowView, /class="table-key-select"/);
  assert.match(css, /\.table-alignment-panel/);
  assert.match(css, /\.theme-light \.table-alignment-panel/);
  assert.match(workflowView, /buildLineMergeRows/);
  assert.match(workflowView, /textChangedLineRows/);
  assert.match(workflowView, /v-for="row in textChangedLineRows"/);
  assert.doesNotMatch(workflowView, /v-for="row in textLineRows"/);
  assert.match(workflowView, /composeLineDraft/);
  assert.match(workflowView, /setDraftFromSource/);
  assert.match(workflowView, /setLineChoice/);
  assert.match(workflowView, /class="conflict-workbench-shell"/);
  assert.doesNotMatch(workflowView, /class="[^"]*conflict-file-rail/);
  assert.doesNotMatch(workflowView, /class="[^"]*conflict-file-list/);
  assert.match(workflowView, /class="text-candidate"/);
  assert.match(workflowView, /class="code-editor-shell"/);
  assert.match(workflowView, /'no-highlight': isLargeTextCandidate/);
  assert.match(workflowView, /class="code-highlight candidate-highlight"/);
  assert.match(workflowView, /ref="candidateHighlight"/);
  assert.match(workflowView, /@scroll="syncCandidateHighlightScroll"/);
  assert.match(workflowView, /v-if="!isLargeTextCandidate"/);
  assert.match(workflowView, /v-html="highlightedTextCandidate"/);
  assert.match(workflowView, /v-html="highlightedCode\(sourceContent\(source\)\)"/);
  assert.match(workflowView, /class="text-line-merge"/);
  assert.match(workflowView, /class="text-line-table"/);
  assert.match(workflowView, /class="text-grid"/);
  assert.match(workflowView, /class="text-pane"/);
  assert.match(workflowView, /class="[^"]*text-conflict-workbench/);
  assert.match(workflowView, /class="[^"]*table-conflict-workbench/);
  assert.match(workflowView, /class="table-workbench-hero"/);
  assert.match(workflowView, /class="table-decision-grid"/);
  assert.match(workflowView, /class="table-conflict-list"/);
  assert.match(workflowView, /class="table-conflict-detail"/);
  assert.match(workflowView, /class="table-side-grid"/);
  assert.match(workflowView, /class="table-side-pane"/);
  assert.match(workflowView, /:class="side"/);
  assert.match(workflowView, /function syncTableSideScroll\(side, event\)/);
  assert.match(workflowView, /:ref="\(?el\)? => setTableSideScroller\(side, el\)"/);
  assert.match(workflowView, /@scroll="syncTableSideScroll\(side, \$event\)"/);
  assert.match(workflowView, /function scrollTablePanesToCell\(cell\)/);
  assert.match(workflowView, /function scrollTableScrollerToCell\(scroller, cell\)/);
  assert.match(workflowView, /scrollTablePanesToCell\(cell\)/);
  assert.match(workflowView, /class="table-preview-pane"/);
  assert.match(workflowView, /ref="tablePreviewScroller"/);
  assert.match(workflowView, /data-table-kind="preview"/);
  assert.match(workflowView, /:data-table-row="row\[column\]\?\.row"/);
  assert.match(workflowView, /:data-table-column="column"/);
  assert.match(workflowView, /tableConflictItems/);
  assert.match(workflowView, /selectedTableConflict/);
  assert.match(workflowView, /const tableSheets = ref\(\[\]\)/);
  assert.match(workflowView, /const activeTableSheetName = ref\(""\)/);
  assert.match(workflowView, /function setActiveTableSheet\(sheetName\)/);
  assert.match(workflowView, /class="table-sheet-tabs"/);
  assert.match(workflowView, /@click="setActiveTableSheet\(sheet\.name\)"/);
  assert.match(workflowView, /sheetName: activeTableSheetName\.value/);
  assert.match(workflowView, /class="[^"]*binary-conflict-workbench/);
  assert.match(workflowView, /class="binary-choice-grid"/);
  assert.match(workflowView, /binaryChoice === 'ours'/);
  assert.match(workflowView, /binaryChoice === 'theirs'/);
  assert.match(workflowView, /class="table-sheet"/);
  assert.match(workflowView, /tableSideCellClass/);
  assert.match(workflowView, /tableSideChoiceLabel/);
  assert.match(workflowView, /class="table-choice-option both"/);
  assert.match(workflowView, /class="table-choice-option none"/);
  assert.match(workflowView, /class="table-choice-segment"/);
  assert.match(workflowView, /<div[^>]*class="table-value-card ours"[^>]*@click="setTableChoice\(selectedTableConflict\.row, selectedTableConflict\.column, 'ours'\)"/);
  assert.match(workflowView, /<div[^>]*class="table-value-card theirs"[^>]*@click="setTableChoice\(selectedTableConflict\.row, selectedTableConflict\.column, 'theirs'\)"/);
  assert.match(workflowView, /class="table-output-mode"/);
  assert.match(workflowView, /v-if="selectedTableConflict\.choice === 'both'"/);
  assert.match(workflowView, /tableBothStrategy/);
  assert.match(workflowView, /const candidateContent = composeTableDraft\(tableMerge\.value, \{ bothStrategy: tableBothStrategy\.value \}\)/);
  assert.match(workflowView, /rowIndex === 0 \? 'HEADER' : `R\$\{rowIndex \+ 1\}`/);
  assert.match(workflowView, /class="table-row-bulk"/);
  assert.match(workflowView, /applySelectedTableRowChoice/);
  assert.doesNotMatch(workflowView, /整行 BOTH/);
  assert.doesNotMatch(workflowView, /整行 NONE/);
  assert.doesNotMatch(workflowView, /同一个候选格子/);
  assert.doesNotMatch(workflowView, /table-raw-candidate/);
  assert.doesNotMatch(workflowView, /候选表格文本/);
  assert.match(workflowView, /current: "CURRENT"/);
  assert.match(workflowView, /base: "BASE"/);
  assert.match(workflowView, /ours: "OURS"/);
  assert.match(workflowView, /theirs: "THEIRS"/);
  assert.match(workflowView, />BOTH</);
  assert.match(workflowView, />NONE</);
  assert.match(workflowView, /class="choice-current"/);
  assert.match(workflowView, /current-\$\{row\.choice\}/);
  assert.match(workflowView, /class="choice-state-dot"/);
  assert.match(workflowView, /candidatePath/);
  assert.match(workflowView, /restoreCandidateResult\(path,/);
  assert.match(workflowView, /rememberCandidateResult\(tableConflict\.value\.path,/);
  assert.match(workflowView, /emit\("candidate-created"/);
  assert.match(workflowView, /@click="openGeneratedCandidate"/);
  assert.match(workflowView, /@click="applyCurrentCandidate"/);
  assert.match(workflowView, /class="candidate-result"/);
  assert.doesNotMatch(workflowView, /conflict-box[^\n]*has-candidates/);
  assert.match(css, /\.conflict-workbench-shell/);
  assert.match(css, /\.conflict-queue-summary/);
  assert.match(css, /\.conflict-row\.candidate-ready/);
  assert.match(css, /\.conflict-row\.candidate-missing/);
  assert.match(css, /\.candidate-ready-pill/);
  assert.match(css, /\.candidate-missing-pill/);
  assert.match(css, /\.workbench-type-pill/);
  assert.match(css, /\.manual-review-pill/);
  assert.match(css, /\.resolved-rebase-box/);
  assert.match(css, /\.resolved-review-row/);
  assert.match(css, /\.resolved-review-actions/);
  assert.match(css, /\.ai-review-btn/);
  assert.match(css, /\.ai-review-btn\.loading/);
  assert.doesNotMatch(css, /\.queue-review-btn/);
  assert.doesNotMatch(css, /\.selection-review-panel/);
  assert.doesNotMatch(css, /\.ai-review-panel-head/);
  assert.doesNotMatch(css, /\.ai-review-pending/);
  assert.match(css, /\.ai-review-result/);
  assert.match(css, /\.ai-review-error/);
  assert.doesNotMatch(css, /\.selection-review-result/);
  assert.match(css, /\.theme-dark \.resolved-rebase-box/);
  assert.doesNotMatch(css, /\.theme-dark \.selection-review-panel/);
  assert.match(css, /\.conflict-risk-tags/);
  assert.match(css, /\.conflict-guidance/);
  assert.match(workflowView, /class="text-button open-workbench-btn"/);
  assert.match(css, /\.conflict-actions \.open-workbench-btn/);
  assert.match(css, /\.theme-dark \.conflict-actions \.open-workbench-btn/);
  assert.match(css, /\.theme-dark \.workbench-type-pill/);
  assert.match(css, /\.theme-dark \.manual-review-pill/);
  assert.doesNotMatch(css, /\.conflict-box\.has-candidates/);
  assert.match(css, /\.code-highlight/);
  assert.match(css, /\.candidate-highlight/);
  assert.match(css, /\.code-editor-shell\.no-highlight textarea/);
  assert.match(css, /\.theme-light \.code-editor-shell\.no-highlight textarea/);
  assert.match(css, /\.theme-dark \.code-editor-shell\.no-highlight textarea/);
  assert.match(css, /\.binary-choice-grid/);
  assert.match(css, /\.table-workbench-hero/);
  assert.match(css, /\.table-sheet-tabs/);
  assert.match(css, /\.table-sheet-tab/);
  assert.match(css, /\.table-decision-grid/);
  assert.match(css, /\.table-side-grid/);
  assert.match(css, /\.table-preview-pane/);
  assert.match(css, /\.table-cell-conflict/);
  assert.match(css, /\.table-cell-auto/);
  assert.match(css, /\.table-choice-segment/);
  assert.match(css, /\.table-output-mode/);
  assert.match(css, /\.table-row-bulk/);
  assert.doesNotMatch(css, /\.table-raw-candidate/);
  assert.match(css, /\.binary-choice-card/);
  assert.match(css, /\.binary-choice-card\.active/);
  assert.match(css, /\.tok-keyword/);
  assert.match(workflowView, /tok-method/);
  assert.match(workflowView, /tok-field/);
  assert.match(workflowView, /tok-variable/);
  assert.match(workflowView, /protectFieldDeclarations\(highlighted, tokens\)/);
  assert.match(workflowView, /protectVariableNames\(highlighted, tokens\)/);
  assert.match(css, /\.tok-method/);
  assert.match(css, /\.tok-field/);
  assert.match(css, /\.tok-variable/);
  assert.match(css, /\.theme-light \.tok-method/);
  assert.match(css, /\.theme-light \.tok-field/);
  assert.match(css, /\.theme-light \.tok-variable/);
  assert.match(css, /\.tok-comment/);
  assert.match(css, /\.tok-string/);
  assert.match(css, /\.tok-merge/);
  assert.ok(css.indexOf(".theme-dark textarea") < css.indexOf(".theme-dark .code-editor-shell textarea"));
  assert.match(css, /\.theme-dark \.code-editor-shell textarea[\s\S]*background: transparent/);
  assert.match(css, /\.theme-light \.code-editor-shell textarea[\s\S]*background: transparent/);
  assert.ok(css.indexOf(".theme-light .code-editor-shell textarea") < css.lastIndexOf(".theme-light .code-editor-shell.no-highlight textarea"));
  assert.ok(css.indexOf(".theme-dark .code-editor-shell textarea") < css.lastIndexOf(".theme-dark .code-editor-shell.no-highlight textarea"));
  assert.match(css, /\.choice-current/);
  assert.match(css, /\.choice-current\.current-ours/);
  assert.match(css, /\.choice-current\.current-theirs/);
  assert.match(css, /\.choice-state-dot/);
  assert.match(css, /\.line-choice \.text-choice-btn:not\(\.active\)/);
  assert.match(css, /\.line-choice \.text-choice-btn\.active::after/);
  assert.match(css, /\.candidate-result/);
  assert.match(css, /\.open-candidate-btn/);
  assert.match(css, /\.text-line-table/);
  assert.match(css, /\.text-choice-btn\.ours/);
  assert.match(css, /\.text-choice-btn\.theirs/);
  assert.match(workflowView, /@click="emit\('action', 'fetch'\)"/);
  assert.match(app, /fetch: zh\.fetchRemote/);
  assert.match(app, /"fetch"/);
  assert.match(workflowView, /selectSection\('staged'\)/);
  assert.match(workflowView, /selectSection\('unstaged'\)/);
  assert.match(workflowView, /selectSection\('untracked'\)/);
  assert.match(workflowView, /selectionQuery/);
  assert.match(workflowView, /visibleSelectableFiles/);
  assert.match(workflowView, /selectVisible\(\)/);
  assert.match(workflowView, /invertVisibleSelection\(\)/);
  assert.match(workflowView, /directoryOptions/);
  assert.match(workflowView, /selectDirectory\(directory\.name\)/);
  assert.match(workflowView, /@click="togglePath\(file\.path, \$event\)"/);
  assert.match(workflowView, /@click\.stop="openFileDetailModal\(file\)"/);
  assert.match(workflowView, /event\??\.shiftKey/);
  assert.match(workflowView, /const detailQueuePath = ref\(""\)/);
  assert.match(workflowView, /const detailQueueFile = computed/);
  assert.match(workflowView, /const fileDiffPreview = ref\(null\)/);
  assert.match(workflowView, /const fileDiffLines = computed/);
  assert.match(workflowView, /function openFileDetailModal\(file\)/);
  assert.match(workflowView, /function closeFileDetailModal\(\)/);
  assert.match(workflowView, /detailQueuePath\.value = file\.path/);
  assert.match(workflowView, /themeMode: \{ type: String, default: "light" \}/);
  assert.match(workflowView, /emit\("load-file-diff"/);
  assert.match(workflowView, /class="text-button file-detail-trigger"/);
  assert.match(workflowView, /class="file-detail-backdrop"/);
  assert.match(workflowView, /:class="`theme-\$\{themeMode\}`"/);
  assert.match(workflowView, /@click="closeFileDetailModal"/);
  assert.match(workflowView, /class="file-detail-dialog"/);
  assert.match(workflowView, /@click\.stop/);
  assert.match(workflowView, /class="file-diff-view"/);
  assert.match(workflowView, /detailQueueFile\.path/);
  assert.match(app, /loadRepoFileDiff as loadRepoFileDiffApi/);
  assert.match(app, /@load-file-diff="loadRepoFileDiff"/);
  assert.match(app, /:theme-mode="themeMode"/);
  assert.match(css, /\.file-detail-trigger/);
  assert.match(css, /\.file-detail-backdrop/);
  assert.match(css, /\.file-detail-dialog/);
  assert.match(css, /\.theme-light \.file-detail-backdrop/);
  assert.match(css, /\.theme-light \.file-detail-dialog/);
  assert.match(css, /\.theme-light \.file-detail-dialog \.file-diff-view/);
  assert.match(css, /\.theme-dark \.file-detail-backdrop/);
  assert.match(css, /\.theme-dark \.file-detail-dialog/);
  assert.match(css, /\.theme-dark \.file-detail-dialog \.file-diff-view/);
  assert.match(css, /\.file-diff-line\.added/);
  assert.match(css, /\.file-diff-line\.removed/);
  assert.doesNotMatch(workflowView, /class="side-column"/);
  assert.doesNotMatch(workflowView, /class="file-preview-panel"/);
  assert.doesNotMatch(workflowView, /window\.open\(fileDiffWindowUrl\.value/);
  assert.match(app, /<Rail/);
  assert.match(app, /<WorkflowView/);
  assert.match(app, /<SettingsView/);
  assert.match(app, /@switch-repo="switchRepo"/);
  assert.doesNotMatch(app, /class="commit-card"/);
  assert.doesNotMatch(app, /class="settings-page"/);
  assert.doesNotMatch(app, /form\.activeProvider/);
  assert.doesNotMatch(app, /form\.providers/);
  assert.doesNotMatch(app, /autocomplete="current-password"/);
  assert.doesNotMatch(app, /type="number" min="0" max="2"/);
  assert.match(gitGraphView, /class="graph-page"/);
  assert.match(gitGraphView, /class="graph-toolbar"/);
  assert.match(gitGraphView, /class="git-graph-list"/);
  assert.match(gitGraphView, /class="graph-titlebar"/);
  assert.match(gitGraphView, /class="graph-branchbar"/);
  assert.match(gitGraphView, /class="graph-column-title"/);
  assert.match(gitGraphView, /class="graph-sidebar"/);
  assert.match(gitGraphView, /class="commit-row"/);
  assert.match(gitGraphView, /class="commit-lanes"/);
  assert.match(gitGraphView, /class="graph-svg"/);
  assert.match(gitGraphView, /class="[^"]*graph-path/);
  assert.match(gitGraphView, /class="[^"]*graph-node/);
  assert.match(gitGraphView, /buildCommitGraphRows/);
  assert.match(gitGraphView, /graphVerticalLanes\(commit\)/);
  assert.match(gitGraphView, /mergeCurvePath\(commit, lane\)/);
  assert.match(gitGraphView, /splitCurvePath\(commit, lane\)/);
  assert.match(gitGraphView, /laneX\(commit\.nodeLane\)/);
  assert.match(gitGraphView, /function verticalPath\(commit, lane\)/);
  assert.match(gitGraphView, /commit\.startsLane && lane === commit\.nodeLane \? 16 : 0/);
  assert.match(gitGraphView, /:d="verticalPath\(commit, lane\)"/);
  assert.match(gitGraphView, /function graphVerticalLanes\(commit\)[\s\S]*const joiningLanes = Array\.isArray\(commit\.mergeJoinLanes\)/);
  assert.match(gitGraphView, /function graphVerticalLanes\(commit\)[\s\S]*!endingLanes\.includes\(lane\) && !joiningLanes\.includes\(lane\)/);
  assert.match(gitGraphView, /function mergeCurvePath\(commit, lane\)[\s\S]*return `M \$\{fromX\} 12 C \$\{fromX\} 17 \$\{toX\} 17 \$\{toX\} \$\{graphRowHeight\}`;/);
  assert.match(gitGraphView, /function splitCurvePath\(commit, lane\)[\s\S]*return `M \$\{fromX\} 0 C \$\{fromX\} 7 \$\{toX\} 7 \$\{toX\} 12`;/);
  assert.match(gitGraphView, /watch\(\s*graphRows/);
  assert.match(gitGraphView, /selectCommit\(rows\[0\]\.hash, \{ force: true \}\)/);
  assert.match(gitGraphView, /function authorInitial/);
  assert.match(gitGraphView, /class="commit-author"/);
  assert.match(gitGraphView, /class="commit-hash"/);
  assert.match(gitGraphView, /class="commit-date"/);
  assert.match(gitGraphView, /ref\.includes\('stash'\)/);
  assert.match(gitGraphView, /ref\.startsWith\('origin\/'\)/);
  assert.match(app, /<GitGraphView/);
  assert.doesNotMatch(app, /git-graph-list/);
  assert.match(graphLayout, /parents\.slice\(1\)/);
  assert.match(graphLayout, /ensureLane/);
  assert.match(graphLayout, /activeBranchLines/);
  assert.match(graphLayout, /clearMatchingLanes/);
  assert.match(graphLayout, /isMerge:/);
  assert.match(graphLayout, /showMergeJoin:/);
  assert.match(graphLayout, /showBranchSplit:/);
  assert.doesNotMatch(app, /v-for="lane in 4"/);
  assert.doesNotMatch(app, /commit\.lane \* 14/);
  assert.match(css, /\.app-shell/);
  assert.match(css, /\.rail/);
  assert.match(css, /\.setup-card/);
  assert.match(css, /\.theme-light/);
  assert.match(css, /\.theme-dark/);
  assert.match(css, /\.theme-dark \.workspace[\s\S]*background: #020817/);
  assert.match(css, /\.rail-collapsed/);
  assert.match(css, /\.rail-tools/);
  assert.match(css, /\.rail-tool/);
  assert.match(css, /\.main-nav/);
  assert.match(css, /\.settings-workspace/);
  assert.match(css, /\.settings-tabs/);
  assert.match(css, /\.settings-card/);
  assert.match(css, /\.setting-alert/);
  assert.match(css, /\.ai-picker/);
  assert.match(css, /\.ai-option/);
  assert.match(css, /\.ai-state/);
  assert.match(css, /\.command-bar/);
  assert.match(css, /\.primary-grid/);
  assert.match(css, /\.commit-card/);
  assert.match(css, /\.metric\.info/);
  assert.match(css, /\.theme-dark \.status-metrics \.metric\.info/);
  assert.match(css, /\.selection-filter/);
  assert.match(css, /\.directory-actions/);
  assert.match(css, /\.queue-row/);
  assert.match(css, /\.file-status-line/);
  assert.match(css, /\.change-kind/);
  assert.match(css, /\.change-added/);
  assert.match(css, /\.change-updated/);
  assert.match(css, /\.change-deleted/);
  assert.match(css, /\.theme-dark \.change-kind/);
  assert.match(css, /\.theme-dark \.change-added/);
  assert.match(css, /\.theme-dark \.change-deleted/);
  assert.match(css, /\.disabled-reason/);
  assert.match(css, /\.btn\.suggest/);
  assert.doesNotMatch(css, /\.btn\.suggest\.assist/);
  assert.match(css, /background: #f59e0b/);
  assert.match(css, /\.theme-dark \.commit-actions \.btn\.suggest/);
  assert.doesNotMatch(css, /\.theme-dark \.commit-actions \.btn\.suggest\.assist/);
  assert.match(graphCss, /\.graph-page/);
  assert.match(graphCss, /\.graph-toolbar/);
  assert.match(graphCss, /\.git-graph-list/);
  assert.match(graphCss, /\.graph-titlebar/);
  assert.match(graphCss, /\.graph-branchbar/);
  assert.match(graphCss, /\.graph-column-title/);
  assert.match(graphCss, /\.graph-sidebar/);
  assert.match(graphCss, /\.commit-row/);
  assert.match(graphCss, /\.commit-lanes/);
  assert.match(graphCss, /\.graph-svg/);
  assert.match(graphCss, /\.graph-path/);
  assert.match(graphCss, /\.graph-curve/);
  assert.match(graphCss, /\.graph-node/);
  assert.match(graphCss, /\.commit-row\.merge/);
  assert.match(graphCss, /\.commit-row\.branch-end/);
  assert.match(graphCss, /\.branch\.remote/);
  assert.match(graphCss, /\.branch\.stash/);
  assert.match(graphCss, /\.commit-author/);
  assert.match(graphCss, /\.commit-hash/);
  assert.match(graphCss, /\.commit-date/);
  assert.match(graphCss, /\.avatar/);
  assert.match(graphCss, /\.commit-row\.selected \.graph-node/);
  assert.doesNotMatch(css, /\.git-graph-list/);
  assert.doesNotMatch(app, /class="graph-card"/);
  assert.doesNotMatch(app, /class="graph-card-head"/);
  assert.doesNotMatch(`${css}\n${graphCss}`, /\.graph-card/);
  assert.doesNotMatch(css, /\.graph-card-head/);
  assert.doesNotMatch(`${css}\n${graphCss}`, /\.lane:nth-child/);
  assert.doesNotMatch(app, /activePanel/);
  assert.doesNotMatch(app, /panel-switch/);
  assert.doesNotMatch(css, /\.panel-switch/);

  assert.doesNotMatch(app, /Sub2API|Admin|Token \u4f7f\u7528\u8d8b\u52bf|\u6a21\u578b\u5206\u5e03|\u7528\u6237\u7ba1\u7406|\u6e20\u9053\u7ba1\u7406|\u8ba2\u9605\u7ba1\u7406/);
  assert.doesNotMatch(`${app}\n${css}`, /浣|鏈|绯|鐢|妯|涓|鈫|鐘|鎭|撳|鏌|鐣|绂|锛|�/);
});
