import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, "..");

test("Vue UI keeps Chinese Git-safe commit-first workbench structure", async () => {
  const app = await readFile(path.join(root, "src", "App.vue"), "utf8");
  const css = await readFile(path.join(root, "src", "styles.css"), "utf8");
  const graphCss = await readFile(path.join(root, "src", "styles", "graph.css"), "utf8");
  const clientApi = await readFile(path.join(root, "src", "client", "api.js"), "utf8");
  const rail = await readFile(path.join(root, "src", "components", "Rail.vue"), "utf8");
  const gitGraphView = await readFile(path.join(root, "src", "views", "GitGraphView.vue"), "utf8");
  const workflowView = await readFile(path.join(root, "src", "views", "WorkflowView.vue"), "utf8");
  const settingsView = await readFile(path.join(root, "src", "views", "SettingsView.vue"), "utf8");
  const settingsModel = await readFile(path.join(root, "src", "settings-model.js"), "utf8");
  const graphLayout = await readFile(path.join(root, "src", "graph-layout.js"), "utf8");

  assert.match(app, /const zh = \{/);
  assert.match(app, /title: "Git 安全提交"/);
  assert.match(app, /aiCommit: "提交选中文件"/);
  assert.match(app, /commitQueue: "提交队列"/);
  assert.match(app, /commitMessage: "提交说明"/);
  assert.match(app, /pushConfirm: "我确认这次推送只包含当前分支上已经完成的提交"/);
  assert.match(app, /forbidPull: "禁止 git pull"/);
  assert.match(app, /forbidReset: "禁止 reset --hard"/);

  assert.match(app, /class="app-shell"/);
  assert.match(rail, /class="rail"/);
  assert.match(rail, /class="setup-card"/);
  assert.match(rail, /class="rail-tools"/);
  assert.match(rail, /class="rail-tool"/);
  assert.match(app, /const themeMode = ref\(/);
  assert.match(app, /const railCollapsed = ref\(false\)/);
  assert.match(app, /function toggleTheme\(\)/);
  assert.match(app, /function toggleRail\(\)/);
  assert.match(rail, /themeMode === 'dark' \? '浅色模式' : '暗色模式'/);
  assert.match(rail, /railCollapsed \? '展开' : '收起'/);
  assert.match(rail, /class="main-nav"/);
  assert.match(app, /const activeView = ref\("workflow"\)/);
  assert.doesNotMatch(app, /const activeSettingsTab = ref\("general"\)/);
  assert.match(settingsView, /const activeSettingsTab = ref\("general"\)/);
  assert.match(settingsView, /const settingsTabs = \[/);
  assert.match(settingsView, /@click="activeSettingsTab = tab\.id"/);
  assert.match(settingsView, /activeSettingsTab === 'ai'/);
  assert.match(settingsView, /activeSettingsTab === 'repo'/);
  assert.match(settingsView, /activeSettingsTab === 'safety'/);
  assert.match(settingsView, /activeSettingsTab === 'local'/);
  assert.match(settingsView, /form\.selectedAi/);
  assert.match(app, /aiInstallations: \[\]/);
  assert.match(app, /const installedAi = computed/);
  assert.match(app, /const selectedAi = computed/);
  assert.match(clientApi, /export async function loadGraph/);
  assert.match(clientApi, /"\/api\/git\/graph"/);
  assert.match(clientApi, /export function openEvents/);
  assert.match(app, /loadAiInstallations\(\)/);
  assert.doesNotMatch(app, /fetch\(/);
  assert.doesNotMatch(app, /api\("\/api\/git\/graph"\)/);
  assert.match(settingsView, /buildSettingsPayload\(form\)/);
  assert.match(settingsView, /fillSettingsFormFromConfig\(form, config/);
  assert.doesNotMatch(app, /hasConfiguredAiKey\(view\.config\)/);
  assert.match(settingsModel, /selectedAi: "codex"/);
  assert.match(settingsModel, /ai: \{\s*selected,/);
  assert.match(settingsView, /class="ai-picker wide"/);
  assert.match(settingsView, /class="ai-option"/);
  assert.match(settingsView, /@click="form\.selectedAi = ai\.id"/);
  assert.match(app, /activeView === 'workflow'/);
  assert.match(app, /activeView === 'graph'/);
  assert.match(app, /activeView === 'settings'/);
  assert.match(app, /<section v-show="activeView === 'workflow'" class="view-pane">/);
  assert.match(app, /<section v-show="activeView === 'graph'" class="view-pane">/);
  assert.match(app, /<section v-show="activeView === 'settings'" class="view-pane">/);
  assert.doesNotMatch(app, /<WorkflowView\s+v-if="activeView === 'workflow'"/);
  assert.doesNotMatch(app, /<GitGraphView\s+v-if="activeView === 'graph'"/);
  assert.doesNotMatch(app, /<SettingsView\s+v-if="activeView === 'settings'"/);
  assert.match(rail, />提交工作流</);
  assert.match(rail, />git 树</);
  assert.match(rail, />设置</);
  assert.match(settingsView, /class="settings-page"/);
  assert.match(settingsView, /class="settings-tabs"/);
  assert.match(settingsView, /class="settings-card"/);
  assert.match(settingsView, /class="setting-alert wide"/);
  assert.match(settingsView, /class="ai-picker wide"/);
  assert.match(workflowView, /class="command-bar"/);
  assert.match(workflowView, /class="commit-card"/);
  assert.match(workflowView, /class="queue-list"/);
  assert.match(workflowView, /class="disabled-reason"/);
  assert.match(workflowView, /emit\("commit"/);
  assert.match(workflowView, /paths: selectedPaths\.value/);
  assert.match(workflowView, /message: commitMessage\.value\.trim\(\)/);
  assert.match(app, /runAction\("commit", payload\)/);
  assert.doesNotMatch(app, /runAction\("ai-commit", payload\)/);
  assert.match(workflowView, /commitResetKey/);
  assert.match(app, /commitResetKey\.value \+= 1/);
  assert.match(workflowView, /emit\("push", \{ confirmed: pushConfirmed\.value \}\)/);
  assert.match(workflowView, /selectSection\('staged'\)/);
  assert.match(workflowView, /selectSection\('unstaged'\)/);
  assert.match(app, /<Rail/);
  assert.match(app, /<WorkflowView/);
  assert.match(app, /<SettingsView/);
  assert.doesNotMatch(app, /class="commit-card"/);
  assert.doesNotMatch(app, /class="settings-page"/);
  assert.doesNotMatch(app, /form\.activeProvider/);
  assert.doesNotMatch(app, /form\.providers/);
  assert.doesNotMatch(app, /autocomplete="current-password"/);
  assert.doesNotMatch(app, /type="number" min="0" max="2"/);
  assert.match(gitGraphView, /class="graph-page"/);
  assert.match(gitGraphView, /class="graph-toolbar"/);
  assert.match(gitGraphView, /class="git-graph-list"/);
  assert.match(gitGraphView, /class="graph-titlebar"/);
  assert.match(gitGraphView, /class="graph-branchbar"/);
  assert.match(gitGraphView, /class="graph-sidebar"/);
  assert.match(gitGraphView, /class="commit-row"/);
  assert.match(gitGraphView, /class="commit-lanes"/);
  assert.match(gitGraphView, /class="mainline"/);
  assert.match(gitGraphView, /buildCommitGraphRows/);
  assert.match(gitGraphView, /v-for="lane in commit\.branchLines"/);
  assert.match(gitGraphView, /class="branchline"/);
  assert.match(gitGraphView, /v-for="lane in commit\.mergeJoinLanes"/);
  assert.match(gitGraphView, /class="merge-join"/);
  assert.match(gitGraphView, /v-for="lane in commit\.branchSplitLanes"/);
  assert.match(gitGraphView, /class="branch-split"/);
  assert.match(gitGraphView, /commit\.nodeLane \* 22/);
  assert.match(app, /<GitGraphView/);
  assert.doesNotMatch(app, /git-graph-list/);
  assert.match(graphLayout, /parents\.slice\(1\)/);
  assert.match(graphLayout, /findVisibleCommonAncestorIndex/);
  assert.match(graphLayout, /isMerge:/);
  assert.match(graphLayout, /showMergeJoin:/);
  assert.match(graphLayout, /showBranchSplit:/);
  assert.doesNotMatch(app, /v-for="lane in 4"/);
  assert.doesNotMatch(app, /commit\.lane \* 14/);
  assert.match(css, /\.app-shell/);
  assert.match(css, /\.rail/);
  assert.match(css, /\.setup-card/);
  assert.match(css, /\.theme-light/);
  assert.match(css, /\.theme-dark/);
  assert.match(css, /\.rail-collapsed/);
  assert.match(css, /\.rail-tools/);
  assert.match(css, /\.rail-tool/);
  assert.match(css, /\.main-nav/);
  assert.match(css, /\.settings-workspace/);
  assert.match(css, /\.settings-tabs/);
  assert.match(css, /\.settings-card/);
  assert.match(css, /\.setting-alert/);
  assert.match(css, /\.ai-picker/);
  assert.match(css, /\.ai-option/);
  assert.match(css, /\.ai-state/);
  assert.match(css, /\.command-bar/);
  assert.match(css, /\.primary-grid/);
  assert.match(css, /\.commit-card/);
  assert.match(css, /\.queue-row/);
  assert.match(css, /\.disabled-reason/);
  assert.match(graphCss, /\.graph-page/);
  assert.match(graphCss, /\.graph-toolbar/);
  assert.match(graphCss, /\.git-graph-list/);
  assert.match(graphCss, /\.graph-titlebar/);
  assert.match(graphCss, /\.graph-branchbar/);
  assert.match(graphCss, /\.graph-sidebar/);
  assert.match(graphCss, /\.commit-row/);
  assert.match(graphCss, /\.commit-lanes/);
  assert.match(graphCss, /\.mainline/);
  assert.match(graphCss, /\.branchline/);
  assert.match(graphCss, /\.merge-join/);
  assert.match(graphCss, /\.branch-split/);
  assert.match(graphCss, /\.commit-row\.merge/);
  assert.match(graphCss, /\.commit-row\.branch-end/);
  assert.doesNotMatch(css, /\.git-graph-list/);
  assert.doesNotMatch(app, /class="graph-card"/);
  assert.doesNotMatch(app, /class="graph-card-head"/);
  assert.doesNotMatch(`${css}\n${graphCss}`, /\.graph-card/);
  assert.doesNotMatch(css, /\.graph-card-head/);
  assert.doesNotMatch(`${css}\n${graphCss}`, /\.lane:nth-child/);
  assert.doesNotMatch(app, /activePanel/);
  assert.doesNotMatch(app, /panel-switch/);
  assert.doesNotMatch(css, /\.panel-switch/);

  assert.doesNotMatch(app, /Sub2API|Admin|Token \u4f7f\u7528\u8d8b\u52bf|\u6a21\u578b\u5206\u5e03|\u7528\u6237\u7ba1\u7406|\u6e20\u9053\u7ba1\u7406|\u8ba2\u9605\u7ba1\u7406/);
  assert.doesNotMatch(`${app}\n${css}`, /浣|鏈|绯|鐢|妯|涓|鈫|鐘|鎭|撳|鏌|鐣|绂|锛|�/);
});
