import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, "..");

test("Vue UI keeps Chinese Git-safe commit-first workbench structure", async () => {
  const app = await readFile(path.join(root, "src", "App.vue"), "utf8");
  const css = await readFile(path.join(root, "src", "styles.css"), "utf8");
  const server = await readFile(path.join(root, "server.mjs"), "utf8");
  const graphCss = await readFile(path.join(root, "src", "styles", "graph.css"), "utf8");
  const clientApi = await readFile(path.join(root, "src", "client", "api.js"), "utf8");
  const rail = await readFile(path.join(root, "src", "components", "Rail.vue"), "utf8");
  const gitGraphView = await readFile(path.join(root, "src", "views", "GitGraphView.vue"), "utf8");
  const workflowView = await readFile(path.join(root, "src", "views", "WorkflowView.vue"), "utf8");
  const settingsView = await readFile(path.join(root, "src", "views", "SettingsView.vue"), "utf8");
  const settingsModel = await readFile(path.join(root, "src", "settings-model.js"), "utf8");
  const graphLayout = await readFile(path.join(root, "src", "graph-layout.js"), "utf8");

  assert.match(app, /const zh = \{/);
  assert.match(app, /title: "Git 安全提交"/);
  assert.match(app, /fetchRemote: "获取远端"/);
  assert.match(app, /openTextWorkbench: "打开文本工作台"/);
  assert.match(app, /exportBinaryConflict: "导出二进制版本"/);
  assert.match(app, /openBinaryWorkbench: "打开二进制工作台"/);
  assert.match(app, /writeConflictCandidate: "生成候选文件"/);
  assert.match(app, /aiCommit: "提交选中文件"/);
  assert.match(app, /commitQueue: "提交队列"/);
  assert.match(app, /commitMessage: "提交说明"/);
  assert.match(app, /forbidPull: "禁止 git pull"/);
  assert.match(app, /forbidReset: "禁止 reset --hard"/);

  assert.match(app, /class="app-shell"/);
  assert.match(rail, /class="rail"/);
  assert.match(rail, /class="setup-card"/);
  assert.match(rail, /class="rail-tools"/);
  assert.match(rail, /class="rail-tool"/);
  assert.match(app, /const themeMode = ref\(/);
  assert.match(app, /const railCollapsed = ref\(false\)/);
  assert.match(app, /function toggleTheme\(\)/);
  assert.match(app, /function toggleRail\(\)/);
  assert.match(rail, /themeMode === 'dark' \? '浅色模式' : '暗色模式'/);
  assert.match(rail, /railCollapsed \? '展开' : '收起'/);
  assert.match(rail, /class="main-nav"/);
  assert.match(app, /const activeView = ref\("workflow"\)/);
  assert.doesNotMatch(app, /const activeSettingsTab = ref\("general"\)/);
  assert.match(settingsView, /const activeSettingsTab = ref\("general"\)/);
  assert.match(settingsView, /const settingsTabs = \[/);
  assert.match(settingsView, /@click="activeSettingsTab = tab\.id"/);
  assert.match(settingsView, /activeSettingsTab === 'ai'/);
  assert.match(settingsView, /activeSettingsTab === 'repo'/);
  assert.match(settingsView, /activeSettingsTab === 'safety'/);
  assert.match(settingsView, /activeSettingsTab === 'local'/);
  assert.match(settingsView, /form\.selectedAi/);
  assert.match(app, /aiInstallations: \[\]/);
  assert.match(app, /const installedAi = computed/);
  assert.match(app, /const selectedAi = computed/);
  assert.match(clientApi, /export async function loadGraph/);
  assert.match(clientApi, /"\/api\/git\/graph"/);
  assert.match(clientApi, /export async function loadTextConflict/);
  assert.match(clientApi, /export async function writeTextCandidate/);
  assert.match(clientApi, /export async function loadTableConflict/);
  assert.match(clientApi, /export async function writeTableCandidate/);
  assert.match(clientApi, /export async function loadBinaryConflict/);
  assert.match(clientApi, /export async function writeBinaryCandidate/);
  assert.match(clientApi, /export async function applyConflictCandidate/);
  assert.match(clientApi, /export async function openRepoFile/);
  assert.match(clientApi, /export async function exportBinaryConflict/);
  assert.match(server, /"\/api\/conflict\/binary\/load"/);
  assert.match(server, /"\/api\/conflict\/binary\/candidate"/);
  assert.match(server, /"\/api\/conflict\/candidate\/apply"/);
  assert.match(clientApi, /export function openEvents/);
  assert.match(server, /openLocalFile\(target\.fullPath\)/);
  assert.doesNotMatch(server, /openLocalFile\(target\.absolute\)/);
  assert.match(app, /loadAiInstallations\(\)/);
  assert.doesNotMatch(app, /fetch\(/);
  assert.doesNotMatch(app, /api\("\/api\/git\/graph"\)/);
  assert.match(settingsView, /buildSettingsPayload\(form\)/);
  assert.match(settingsView, /fillSettingsFormFromConfig\(form, config/);
  assert.match(settingsView, /function chooseRepoFolder\(\)/);
  assert.match(settingsView, /emit\("choose-repo-folder"/);
  assert.match(settingsView, /if \(path\) \{\s*form\.repoPath = path;\s*emit\("save", buildSettingsPayload\(form\)\);\s*\}/);
  assert.match(settingsView, /class="repo-path-picker wide"/);
  assert.match(settingsView, /v-model="form\.repoPath"/);
  assert.match(settingsView, /@click="chooseRepoFolder"/);
  assert.match(settingsView, /class="repo-history wide"/);
  assert.match(settingsView, /v-for="repo in form\.repositories"/);
  assert.match(settingsView, /@click="switchRepo\(repo\)"/);
  assert.match(settingsView, /emit\("switch-repo"/);
  assert.doesNotMatch(app, /hasConfiguredAiKey\(view\.config\)/);
  assert.match(settingsModel, /selectedAi: "codex"/);
  assert.match(settingsModel, /ai: \{\s*selected,/);
  assert.match(settingsView, /class="ai-picker wide"/);
  assert.match(settingsView, /class="ai-option"/);
  assert.match(settingsView, /@click="form\.selectedAi = ai\.id"/);
  assert.match(app, /activeView === 'workflow'/);
  assert.match(app, /activeView === 'graph'/);
  assert.match(app, /activeView === 'settings'/);
  assert.match(app, /<section v-show="activeView === 'workflow'" class="view-pane">/);
  assert.match(app, /<section v-show="activeView === 'graph'" class="view-pane">/);
  assert.match(app, /<section v-show="activeView === 'settings'" class="view-pane">/);
  assert.doesNotMatch(app, /<WorkflowView\s+v-if="activeView === 'workflow'"/);
  assert.doesNotMatch(app, /<GitGraphView\s+v-if="activeView === 'graph'"/);
  assert.doesNotMatch(app, /<SettingsView\s+v-if="activeView === 'settings'"/);
  assert.match(rail, />提交工作流</);
  assert.match(rail, />git 树</);
  assert.match(rail, />设置</);
  assert.match(settingsView, /class="settings-page"/);
  assert.match(settingsView, /class="settings-tabs"/);
  assert.match(settingsView, /class="settings-card"/);
  assert.match(settingsView, /class="setting-alert wide"/);
  assert.match(settingsView, /class="ai-picker wide"/);
  assert.match(workflowView, /class="command-bar"/);
  assert.match(workflowView, /class="commit-card"/);
  assert.match(workflowView, /class="queue-list"/);
  assert.match(workflowView, /class="disabled-reason"/);
  assert.match(workflowView, /emit\("commit"/);
  assert.match(workflowView, /paths: selectedPaths\.value/);
  assert.match(workflowView, /async function ensureCommitMessage/);
  assert.match(workflowView, /const message = await ensureCommitMessage\(\)/);
  assert.match(workflowView, /emit\("commit", \{ paths: selectedPaths\.value, message \}\)/);
  assert.doesNotMatch(workflowView, /if \(!commitMessage\.value\.trim\(\)\) return/);
  assert.match(workflowView, /class="commit-actions"[\s\S]*@click="suggestMessage"[\s\S]*@click="runCommit"/);
  assert.match(app, /runAction\("commit", payload\)/);
  assert.doesNotMatch(app, /runAction\("ai-commit", payload\)/);
  assert.match(app, /const conflictCandidates = ref\(\{\}\)/);
  assert.match(app, /const displayedBlockers = computed/);
  assert.match(app, /function rememberConflictCandidate\(payload\)/);
  assert.match(app, /applyConflictCandidate as applyConflictCandidateApi/);
  assert.match(app, /async function applyConflictCandidate\(payload, done\)/);
  assert.match(app, /unmerged files present/);
  assert.match(app, /formatBlocker\(blocker, candidateCount, unmergedCount\)/);
  assert.match(app, /候选文件只是草稿，还没有应用到原冲突文件/);
  assert.match(app, /原文件仍包含冲突标记/);
  assert.match(app, /工作区检查未通过/);
  assert.match(workflowView, /commitResetKey/);
  assert.match(app, /commitResetKey\.value \+= 1/);
  assert.match(workflowView, /emit\("action", "push", \{ confirmed: true \}\)/);
  assert.doesNotMatch(workflowView, /emit\("push", \{ confirmed: true \}\)/);
  assert.doesNotMatch(workflowView, /"push", "load-text-conflict"/);
  assert.doesNotMatch(app, /@push="runPush"/);
  assert.match(workflowView, /emit\("action", "continue-rebase-and-push", \{ confirmed: true \}\)/);
  assert.match(workflowView, /emit\("action", "sync"\)/);
  assert.doesNotMatch(workflowView, /emit\("action", "ai-sync"\)/);
  assert.match(workflowView, /const rebaseInProgress = computed/);
  assert.match(workflowView, /继续变基并推送/);
  assert.match(workflowView, /rebaseInProgress\.value/);
  assert.match(workflowView, /class="[^"]*conflict-box/);
  assert.match(workflowView, /function openTextWorkbench\(path\)/);
  assert.match(workflowView, /function openTableWorkbench\(path\)/);
  assert.match(workflowView, /function openBinaryWorkbench\(path\)/);
  assert.match(workflowView, /csv\|tsv\|xlsx/);
  assert.match(app, /action === "sync"/);
  assert.match(app, /loadConfigAndState\(\), loadGraph\(\)/);
  assert.match(workflowView, /function saveTextCandidate\(\)/);
  assert.match(workflowView, /function saveTableCandidate\(\)/);
  assert.match(workflowView, /function saveBinaryCandidate\(\)/);
  assert.match(workflowView, /function openGeneratedCandidate\(\)/);
  assert.match(workflowView, /candidateResultsByPath/);
  assert.match(workflowView, /function rememberCandidateResult\(path, candidate, message\)/);
  assert.match(workflowView, /function restoreCandidateResult\(path, fallbackMessage\)/);
  assert.match(workflowView, /"candidate-created"/);
  assert.match(workflowView, /function conflictCandidateFor\(file\)/);
  assert.match(workflowView, /function conflictRowClass\(file\)/);
  assert.match(workflowView, /"apply-candidate"/);
  assert.match(workflowView, /function applyCandidateFor\(file\)/);
  assert.match(workflowView, /应用候选并暂存/);
  assert.match(workflowView, /candidate-ready/);
  assert.match(workflowView, /candidate-missing/);
  assert.match(workflowView, /候选已生成/);
  assert.match(workflowView, /待生成候选/);
  assert.match(workflowView, /function highlightedCode\(content\)/);
  assert.match(workflowView, /function protectFieldDeclarations\(content, tokens\)/);
  assert.match(workflowView, /function protectVariableNames\(content, tokens\)/);
  assert.match(workflowView, /typeof maybeName === "string"/);
  assert.match(workflowView, /function syncCandidateHighlightScroll\(event\)/);
  assert.match(workflowView, /function exportBinary\(path\)/);
  assert.match(workflowView, /buildTableMerge/);
  assert.match(workflowView, /composeTableDraft/);
  assert.match(workflowView, /composeTableRows/);
  assert.match(workflowView, /tableChoiceSummary/);
  assert.match(workflowView, /buildLineMergeRows/);
  assert.match(workflowView, /composeLineDraft/);
  assert.match(workflowView, /setDraftFromSource/);
  assert.match(workflowView, /setLineChoice/);
  assert.match(workflowView, /class="conflict-workbench-shell"/);
  assert.doesNotMatch(workflowView, /class="[^"]*conflict-file-rail/);
  assert.doesNotMatch(workflowView, /class="[^"]*conflict-file-list/);
  assert.match(workflowView, /class="text-candidate"/);
  assert.match(workflowView, /class="code-editor-shell"/);
  assert.match(workflowView, /class="code-highlight candidate-highlight"/);
  assert.match(workflowView, /ref="candidateHighlight"/);
  assert.match(workflowView, /@scroll="syncCandidateHighlightScroll"/);
  assert.match(workflowView, /v-html="highlightedCode\(textCandidate\)"/);
  assert.match(workflowView, /v-html="highlightedCode\(sourceContent\(source\)\)"/);
  assert.match(workflowView, /class="text-line-merge"/);
  assert.match(workflowView, /class="text-line-table"/);
  assert.match(workflowView, /class="text-grid"/);
  assert.match(workflowView, /class="text-pane"/);
  assert.match(workflowView, /class="[^"]*text-conflict-workbench/);
  assert.match(workflowView, /class="[^"]*table-conflict-workbench/);
  assert.match(workflowView, /class="table-workbench-hero"/);
  assert.match(workflowView, /class="table-decision-grid"/);
  assert.match(workflowView, /class="table-conflict-list"/);
  assert.match(workflowView, /class="table-conflict-detail"/);
  assert.match(workflowView, /class="table-side-grid"/);
  assert.match(workflowView, /class="table-side-pane"/);
  assert.match(workflowView, /:class="side"/);
  assert.match(workflowView, /class="table-preview-pane"/);
  assert.match(workflowView, /tableConflictItems/);
  assert.match(workflowView, /selectedTableConflict/);
  assert.match(workflowView, /class="[^"]*binary-conflict-workbench/);
  assert.match(workflowView, /class="binary-choice-grid"/);
  assert.match(workflowView, /binaryChoice === 'ours'/);
  assert.match(workflowView, /binaryChoice === 'theirs'/);
  assert.match(workflowView, /class="table-sheet"/);
  assert.match(workflowView, /tableSideCellClass/);
  assert.match(workflowView, /tableSideChoiceLabel/);
  assert.match(workflowView, /class="table-choice-option both"/);
  assert.match(workflowView, /class="table-choice-option none"/);
  assert.match(workflowView, /class="table-choice-segment"/);
  assert.match(workflowView, /class="table-output-mode"/);
  assert.match(workflowView, /v-if="selectedTableConflict\.choice === 'both'"/);
  assert.match(workflowView, /tableBothStrategy/);
  assert.match(workflowView, /class="table-row-bulk"/);
  assert.match(workflowView, /applySelectedTableRowChoice/);
  assert.doesNotMatch(workflowView, /整行 BOTH/);
  assert.doesNotMatch(workflowView, /整行 NONE/);
  assert.doesNotMatch(workflowView, /同一个候选格子/);
  assert.doesNotMatch(workflowView, /table-raw-candidate/);
  assert.doesNotMatch(workflowView, /候选表格文本/);
  assert.match(workflowView, /current: "CURRENT"/);
  assert.match(workflowView, /base: "BASE"/);
  assert.match(workflowView, /ours: "OURS"/);
  assert.match(workflowView, /theirs: "THEIRS"/);
  assert.match(workflowView, />BOTH</);
  assert.match(workflowView, />NONE</);
  assert.match(workflowView, /class="choice-current"/);
  assert.match(workflowView, /class="choice-state-dot"/);
  assert.match(workflowView, /candidatePath/);
  assert.match(workflowView, /restoreCandidateResult\(path,/);
  assert.match(workflowView, /rememberCandidateResult\(tableConflict\.value\.path,/);
  assert.match(workflowView, /emit\("candidate-created"/);
  assert.match(workflowView, /@click="openGeneratedCandidate"/);
  assert.match(workflowView, /@click="applyCurrentCandidate"/);
  assert.match(workflowView, /class="candidate-result"/);
  assert.doesNotMatch(workflowView, /conflict-box[^\n]*has-candidates/);
  assert.match(css, /\.conflict-workbench-shell/);
  assert.match(css, /\.conflict-row\.candidate-ready/);
  assert.match(css, /\.conflict-row\.candidate-missing/);
  assert.match(css, /\.candidate-ready-pill/);
  assert.match(css, /\.candidate-missing-pill/);
  assert.doesNotMatch(css, /\.conflict-box\.has-candidates/);
  assert.match(css, /\.code-highlight/);
  assert.match(css, /\.candidate-highlight/);
  assert.match(css, /\.binary-choice-grid/);
  assert.match(css, /\.table-workbench-hero/);
  assert.match(css, /\.table-decision-grid/);
  assert.match(css, /\.table-side-grid/);
  assert.match(css, /\.table-preview-pane/);
  assert.match(css, /\.table-cell-conflict/);
  assert.match(css, /\.table-cell-auto/);
  assert.match(css, /\.table-choice-segment/);
  assert.match(css, /\.table-output-mode/);
  assert.match(css, /\.table-row-bulk/);
  assert.doesNotMatch(css, /\.table-raw-candidate/);
  assert.match(css, /\.binary-choice-card/);
  assert.match(css, /\.binary-choice-card\.active/);
  assert.match(css, /\.tok-keyword/);
  assert.match(workflowView, /tok-method/);
  assert.match(workflowView, /tok-field/);
  assert.match(workflowView, /tok-variable/);
  assert.match(workflowView, /protectFieldDeclarations\(highlighted, tokens\)/);
  assert.match(workflowView, /protectVariableNames\(highlighted, tokens\)/);
  assert.match(css, /\.tok-method/);
  assert.match(css, /\.tok-field/);
  assert.match(css, /\.tok-variable/);
  assert.match(css, /\.theme-light \.tok-method/);
  assert.match(css, /\.theme-light \.tok-field/);
  assert.match(css, /\.theme-light \.tok-variable/);
  assert.match(css, /\.tok-comment/);
  assert.match(css, /\.tok-string/);
  assert.match(css, /\.tok-merge/);
  assert.ok(css.indexOf(".theme-dark textarea") < css.indexOf(".theme-dark .code-editor-shell textarea"));
  assert.match(css, /\.theme-dark \.code-editor-shell textarea[\s\S]*background: transparent/);
  assert.match(css, /\.theme-light \.code-editor-shell textarea[\s\S]*background: transparent/);
  assert.match(css, /\.choice-current/);
  assert.match(css, /\.choice-state-dot/);
  assert.match(css, /\.line-choice \.text-choice-btn\.active::after/);
  assert.match(css, /\.candidate-result/);
  assert.match(css, /\.open-candidate-btn/);
  assert.match(css, /\.text-line-table/);
  assert.match(css, /\.text-choice-btn\.ours/);
  assert.match(css, /\.text-choice-btn\.theirs/);
  assert.match(workflowView, /@click="emit\('action', 'fetch'\)"/);
  assert.match(app, /fetch: zh\.fetchRemote/);
  assert.match(app, /action === "fetch"/);
  assert.match(workflowView, /selectSection\('staged'\)/);
  assert.match(workflowView, /selectSection\('unstaged'\)/);
  assert.match(workflowView, /selectSection\('untracked'\)/);
  assert.match(workflowView, /selectionQuery/);
  assert.match(workflowView, /visibleSelectableFiles/);
  assert.match(workflowView, /selectVisible\(\)/);
  assert.match(workflowView, /invertVisibleSelection\(\)/);
  assert.match(workflowView, /directoryOptions/);
  assert.match(workflowView, /selectDirectory\(directory\.name\)/);
  assert.match(workflowView, /togglePath\(file\.path, \$event\)/);
  assert.match(workflowView, /event\??\.shiftKey/);
  assert.match(app, /<Rail/);
  assert.match(app, /<WorkflowView/);
  assert.match(app, /<SettingsView/);
  assert.match(app, /@switch-repo="switchRepo"/);
  assert.doesNotMatch(app, /class="commit-card"/);
  assert.doesNotMatch(app, /class="settings-page"/);
  assert.doesNotMatch(app, /form\.activeProvider/);
  assert.doesNotMatch(app, /form\.providers/);
  assert.doesNotMatch(app, /autocomplete="current-password"/);
  assert.doesNotMatch(app, /type="number" min="0" max="2"/);
  assert.match(gitGraphView, /class="graph-page"/);
  assert.match(gitGraphView, /class="graph-toolbar"/);
  assert.match(gitGraphView, /class="git-graph-list"/);
  assert.match(gitGraphView, /class="graph-titlebar"/);
  assert.match(gitGraphView, /class="graph-branchbar"/);
  assert.match(gitGraphView, /class="graph-sidebar"/);
  assert.match(gitGraphView, /class="commit-row"/);
  assert.match(gitGraphView, /class="commit-lanes"/);
  assert.match(gitGraphView, /class="mainline"/);
  assert.match(gitGraphView, /buildCommitGraphRows/);
  assert.match(gitGraphView, /v-for="lane in commit\.branchLines"/);
  assert.match(gitGraphView, /class="branchline"/);
  assert.match(gitGraphView, /v-for="lane in commit\.mergeJoinLanes"/);
  assert.match(gitGraphView, /class="merge-join"/);
  assert.match(gitGraphView, /v-for="lane in commit\.branchSplitLanes"/);
  assert.match(gitGraphView, /class="branch-split"/);
  assert.match(gitGraphView, /commit\.nodeLane \* 22/);
  assert.match(app, /<GitGraphView/);
  assert.doesNotMatch(app, /git-graph-list/);
  assert.match(graphLayout, /parents\.slice\(1\)/);
  assert.match(graphLayout, /findVisibleCommonAncestorIndex/);
  assert.match(graphLayout, /isMerge:/);
  assert.match(graphLayout, /showMergeJoin:/);
  assert.match(graphLayout, /showBranchSplit:/);
  assert.doesNotMatch(app, /v-for="lane in 4"/);
  assert.doesNotMatch(app, /commit\.lane \* 14/);
  assert.match(css, /\.app-shell/);
  assert.match(css, /\.rail/);
  assert.match(css, /\.setup-card/);
  assert.match(css, /\.theme-light/);
  assert.match(css, /\.theme-dark/);
  assert.match(css, /\.rail-collapsed/);
  assert.match(css, /\.rail-tools/);
  assert.match(css, /\.rail-tool/);
  assert.match(css, /\.main-nav/);
  assert.match(css, /\.settings-workspace/);
  assert.match(css, /\.settings-tabs/);
  assert.match(css, /\.settings-card/);
  assert.match(css, /\.setting-alert/);
  assert.match(css, /\.ai-picker/);
  assert.match(css, /\.ai-option/);
  assert.match(css, /\.ai-state/);
  assert.match(css, /\.command-bar/);
  assert.match(css, /\.primary-grid/);
  assert.match(css, /\.commit-card/);
  assert.match(css, /\.selection-filter/);
  assert.match(css, /\.directory-actions/);
  assert.match(css, /\.queue-row/);
  assert.match(css, /\.disabled-reason/);
  assert.match(css, /\.btn\.suggest/);
  assert.match(css, /background: #f59e0b/);
  assert.match(css, /\.theme-dark \.commit-actions \.btn\.suggest/);
  assert.match(graphCss, /\.graph-page/);
  assert.match(graphCss, /\.graph-toolbar/);
  assert.match(graphCss, /\.git-graph-list/);
  assert.match(graphCss, /\.graph-titlebar/);
  assert.match(graphCss, /\.graph-branchbar/);
  assert.match(graphCss, /\.graph-sidebar/);
  assert.match(graphCss, /\.commit-row/);
  assert.match(graphCss, /\.commit-lanes/);
  assert.match(graphCss, /\.mainline/);
  assert.match(graphCss, /\.branchline/);
  assert.match(graphCss, /\.merge-join/);
  assert.match(graphCss, /\.branch-split/);
  assert.match(graphCss, /\.commit-row\.merge/);
  assert.match(graphCss, /\.commit-row\.branch-end/);
  assert.doesNotMatch(css, /\.git-graph-list/);
  assert.doesNotMatch(app, /class="graph-card"/);
  assert.doesNotMatch(app, /class="graph-card-head"/);
  assert.doesNotMatch(`${css}\n${graphCss}`, /\.graph-card/);
  assert.doesNotMatch(css, /\.graph-card-head/);
  assert.doesNotMatch(`${css}\n${graphCss}`, /\.lane:nth-child/);
  assert.doesNotMatch(app, /activePanel/);
  assert.doesNotMatch(app, /panel-switch/);
  assert.doesNotMatch(css, /\.panel-switch/);

  assert.doesNotMatch(app, /Sub2API|Admin|Token \u4f7f\u7528\u8d8b\u52bf|\u6a21\u578b\u5206\u5e03|\u7528\u6237\u7ba1\u7406|\u6e20\u9053\u7ba1\u7406|\u8ba2\u9605\u7ba1\u7406/);
  assert.doesNotMatch(`${app}\n${css}`, /浣|鏈|绯|鐢|妯|涓|鈫|鐘|鎭|撳|鏌|鐣|绂|锛|�/);
});
